### ISSUE TITLE
fraud handling on snap PaymentController

### ISSUE THREAD

**Issue by audrynyonata** [veritrans/SNAP-Magento#17]
I have some questions about `notificationAction()` in `../Midtrans/Snap/controllers/PaymentController.php`:

1. How does the controller know that the request came from MIDTRANS and not someone unresponsible who can **easily post a fake request** stating the payment is completed?

2. All order with expired snap transactions is labeled as fraud, which is quite a strong accusation. on line 347 it is written: 
`else if ($transaction == 'cancel' || $transaction == 'deny' ) {`
&nbsp;&nbsp;&nbsp;&nbsp;`$order->setStatus(Mage_Sales_Model_Order::STATE_CANCELED);`  
`}`   
but on line 376 it is redundant:
`else if ($transaction == 'cancel') {`  
&nbsp;&nbsp;&nbsp;&nbsp;`$order->setStatus(Mage_Sales_Model_Order::STATE_CANCELED);`
`} else {`
&nbsp;&nbsp;&nbsp;&nbsp;`$order->setStatus(Mage_Sales_Model_Order::STATUS_FRAUD);`
`}`  
Could it be one of the redundant if-blocks is supposed to handle `$transaction == 'expire'`? or maybe I'm just being _sok tahu_.

Thank you.

**Comment by rizdaprasetya** [comment]
Hi @audrynyonata thanks for asking.

1) Within this piece of code
https://github.com/veritrans/SNAP-Magento/blob/2ff431a2bdc9e05a2b5791be35800ff7af828c63/app/code/community/Midtrans/Snap/controllers/PaymentController.php#L315
When `Veritrans_Notification` object created, Veritrans library will do `get status` API request, based on `transaction_id` received on the POST request. So that way the `payment_status` is safely verified coming from Midtrans API.

2) Valid points, this if-else block haven't been reviewed for a while. Which likely contains mistakes.
> All order with expired snap transactions is labeled as fraud

Right, this should not happen. The buggy code is
https://github.com/veritrans/SNAP-Magento/blob/2ff431a2bdc9e05a2b5791be35800ff7af828c63/app/code/community/Midtrans/Snap/controllers/PaymentController.php#L379-L381
The correct default `else` should be `STATE_CANCELED` instead of fraud

> but on line 376 it is redundant:

https://github.com/veritrans/SNAP-Magento/blob/2ff431a2bdc9e05a2b5791be35800ff7af828c63/app/code/community/Midtrans/Snap/controllers/PaymentController.php#L376-L378
Right, that is redundant, I'm guessing the coder wanted to copy-paste the `cancel` block and rename it to `expire`.
should be `expire`.

> or maybe I'm just being sok tahu.

Don't worry those are valid questions and help us spot bugs within the code (that's the point we open source the code). Thanks, we appreciate it.

I'll let the repo maintainer check the issue and see for possible fix.
Thanks!

**Comment by rizdaprasetya** [comment]
Hi @audrynyonata 
This should have been addressed now
https://github.com/veritrans/SNAP-Magento/pull/19

Let us know if you have any other concerns, else this issue will be closed.
Thanks.

**Comment by audrynyonata** [comment]
Thank you!
